# Generated by Django 2.0.5 on 2019-07-07 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pnaija', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='officeid',
            new_name='office',
        ),
    ]
