# Generated by Django 2.0.5 on 2019-07-08 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pnaija', '0003_auto_20190708_0542'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='title',
            field=models.CharField(choices=[(1, 'Enquires'), (2, 'Report Critical Situation'), (3, 'Give Us Your Suggestions')], default=1, max_length=10),
        ),
    ]
