# Generated by Django 2.0.5 on 2019-07-08 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pnaija', '0005_auto_20190708_0706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='user',
        ),
        migrations.AddField(
            model_name='feedback',
            name='name',
            field=models.CharField(default='jhhjdf', max_length=100),
        ),
    ]
