# Generated by Django 2.0.5 on 2019-07-08 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pnaija', '0006_auto_20190708_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
