# Generated by Django 2.0.5 on 2019-07-08 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pnaija', '0007_auto_20190708_0726'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='email',
            field=models.EmailField(default=55, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='title',
            field=models.IntegerField(choices=[(1, 'Enquires'), (2, 'Report Critical Situation'), (3, 'Give Us Your Suggestions')], default=1),
        ),
    ]
