# Generated by Django 2.0.5 on 2019-07-08 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pnaija', '0009_feedback_createdat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-createdAt']},
        ),
        migrations.AddField(
            model_name='feedback',
            name='location',
            field=models.TextField(default='null'),
        ),
    ]
