# Generated by Django 2.0.5 on 2019-07-08 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pnaija', '0010_auto_20190708_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='location',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
